# Generated by Django 5.2.3 on 2025-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derangement',
            fields=[
                ('id_db', models.AutoField(primary_key=True, serialize=False)),
                ('id_drgt', models.BigIntegerField()),
                ('service_technique', models.CharField(max_length=50)),
                ('ncli', models.CharField(blank=True, max_length=50, null=True)),
                ('nd', models.CharField(blank=True, max_length=50, null=True)),
                ('etat_dossier', models.CharField(max_length=50)),
                ('produit', models.CharField(max_length=50)),
                ('nom_du_client', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_du_client', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_client', models.CharField(blank=True, max_length=30, null=True)),
                ('commentaire_contact', models.TextField(blank=True, null=True)),
                ('c_gest', models.CharField(blank=True, max_length=50, null=True)),
                ('segment', models.CharField(blank=True, max_length=50, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('date_msv_acces_reseau', models.DateTimeField(blank=True, null=True)),
                ('acces_rx', models.CharField(blank=True, max_length=100, null=True)),
                ('date_resil_acces_rx', models.DateTimeField(blank=True, null=True)),
                ('etat_drgt', models.CharField(blank=True, max_length=50, null=True)),
                ('date_si', models.DateTimeField(blank=True, null=True)),
                ('agent_sig', models.CharField(blank=True, max_length=100, null=True)),
                ('libel_orig', models.TextField(blank=True, null=True)),
                ('libel_sig', models.TextField(blank=True, null=True)),
                ('commentaire_sig', models.TextField(blank=True, null=True)),
                ('ss_reseau', models.CharField(blank=True, max_length=50, null=True)),
                ('secteur_geo', models.CharField(blank=True, max_length=50, null=True)),
                ('zone_rs', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle_commune', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle_quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle_voie', models.CharField(blank=True, max_length=100, null=True)),
                ('nvoie', models.CharField(blank=True, max_length=100, null=True)),
                ('id_drgt_collectif', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ess', models.DateTimeField(blank=True, null=True)),
                ('priorite_drgt', models.CharField(blank=True, max_length=50, null=True)),
                ('option_atr_h', models.CharField(blank=True, max_length=20, null=True)),
                ('priorite_serv', models.CharField(blank=True, max_length=50, null=True)),
                ('specialite', models.CharField(blank=True, max_length=50, null=True)),
                ('result_ess', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire_essai', models.TextField(blank=True, null=True)),
                ('agent_ess', models.CharField(blank=True, max_length=100, null=True)),
                ('date_demande_int', models.DateTimeField(blank=True, null=True)),
                ('commentaire_interv', models.TextField(blank=True, null=True)),
                ('agent_dem_int', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ot', models.CharField(blank=True, max_length=50, null=True)),
                ('type_ot', models.CharField(blank=True, max_length=50, null=True)),
                ('date_etat_ot', models.DateTimeField(blank=True, null=True)),
                ('etat_ot', models.CharField(blank=True, max_length=50, null=True)),
                ('date_rv', models.DateTimeField(blank=True, null=True)),
                ('rdv', models.CharField(blank=True, max_length=50, null=True)),
                ('code_ui', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle_ui', models.CharField(blank=True, max_length=100, null=True)),
                ('equipe', models.CharField(blank=True, max_length=50, null=True)),
                ('date_releve_prevision', models.DateTimeField(blank=True, null=True)),
                ('date_releve', models.DateTimeField(blank=True, null=True)),
                ('respect_delai', models.CharField(blank=True, max_length=20, null=True)),
                ('libelle_releve', models.TextField(blank=True, null=True)),
                ('libelle_cause', models.TextField(blank=True, null=True)),
                ('libelle_localis', models.TextField(blank=True, null=True)),
                ('commentaire_releve', models.TextField(blank=True, null=True)),
                ('agent_releve', models.CharField(blank=True, max_length=100, null=True)),
                ('techno', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('cause', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('semaine', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Relevé',
                'verbose_name_plural': 'Relevés',
            },
        ),
    ]
